apiVersion: apps/v1
kind: Deployment
metadata:
  name: finflow-notification-service
  namespace: finflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finflow-notification-service
  template:
    metadata:
      labels:
        app: finflow-notification-service
    spec:
      containers:
        - name: notification-service
          image: du0408/finflow-notification-service:latest
          ports:
            - containerPort: 8002
          envFrom:
            - configMapRef:
                name: finflow-config
            - secretRef:
                name: finflow-secrets
          readinessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: finflow-notification-service
  namespace: finflow
spec:
  selector:
    app: finflow-notification-service
  ports:
    - port: 8002
      targetPort: 8002